private lateinit var database: AppDatabase

override fun onCreate(savedInstanceState: Bundle?) {
    // ...
    database = AppDatabase.getInstance(this)
    // ...
}

private fun saveCard() {
    // ...
    lifecycleScope.launch {
        // ...
        database.cardDao().insertCard(card)
        // ...
    }
}
